""" version which can be consumed from within the module """
VERSION_STR = "0.0.24"
DESCRIPTION = "faster read of gzip files using a pipe to zcat(1)"
APP_NAME = "pypipegzip"
LOGGER_NAME = "pypipegzip"
